// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9oZq9mQH1btfKZEQXqhIgYtK7nsPMobo',
    appId: '1:956817446616:web:86907fd2c58b09a5cb29ad',
    messagingSenderId: '956817446616',
    projectId: 'labflutter-grami',
    authDomain: 'labflutter-grami.firebaseapp.com',
    storageBucket: 'labflutter-grami.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLo8AeNg7ErIU9VhmNeAzWHFa2sLQdYJo',
    appId: '1:956817446616:android:ad043aa44efabc5ccb29ad',
    messagingSenderId: '956817446616',
    projectId: 'labflutter-grami',
    storageBucket: 'labflutter-grami.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6TyG-ULqLdnkZetqtT4UrxrIVfVYlnN8',
    appId: '1:956817446616:ios:304ee5b46cbf618dcb29ad',
    messagingSenderId: '956817446616',
    projectId: 'labflutter-grami',
    storageBucket: 'labflutter-grami.firebasestorage.app',
    iosBundleId: 'com.grami.gramiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6TyG-ULqLdnkZetqtT4UrxrIVfVYlnN8',
    appId: '1:956817446616:ios:304ee5b46cbf618dcb29ad',
    messagingSenderId: '956817446616',
    projectId: 'labflutter-grami',
    storageBucket: 'labflutter-grami.firebasestorage.app',
    iosBundleId: 'com.grami.gramiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9oZq9mQH1btfKZEQXqhIgYtK7nsPMobo',
    appId: '1:956817446616:web:c9a9ba77dc0d39efcb29ad',
    messagingSenderId: '956817446616',
    projectId: 'labflutter-grami',
    authDomain: 'labflutter-grami.firebaseapp.com',
    storageBucket: 'labflutter-grami.firebasestorage.app',
  );
}
